### ISSUE TITLE
Claim dwyl Internet Company Handles

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/brand#10]
**Important**
- [x] Github https://github.com/dwyl
- [ ] Facebook - https://www.facebook.com/dwylhq username too short [Claim sent]
- [x] Twitter https://twitter.com/dwyl
- [ ] Instagram - https://www.instagram.com/dwylhq/ taken [Claim sent]
- [ ] YouTube - https://www.youtube.com/channel/UCUTgHTqMaUTRopfpRepjcTQ need >100 subscribers
- [ ] Google Plus - https://plus.google.com/102588574227316532027 need 10 followers
- [x] LinkedIn https://www.linkedin.com/company/dwyl
- [x] Medium - https://medium.com/dwyl

**Additional**
- [ ] Snapchat - taken
- [ ] Tumblr - taken http://dwyl.tumblr.com/
- [ ] Pinterest - taken https://uk.pinterest.com/dwyl/
- [ ] Reddit - taken https://www.reddit.com/user/dwyl

**Comment by iteles** [comment]
@markwilliamfirth On youtube: https://www.youtube.com/channel/UCItdEQk0-lGLm8JhOfoLxkQ

**Comment by markwilliamfirth** [comment]
@iteles can we delete the old one? Created a new one as I couldn't find it and it wasn't linked to a G+ business page
