### ISSUE TITLE
LinkedIn decribes DWYL as "non-profit"

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/brand#6]
I'm assuming this needs updating?

**Comment by iteles** [comment]
@markwilliamfirth Could you please add a screenshot? I can't see that:

<img width="789" alt="screen shot 2017-02-07 at 13 56 38" src="https://cloud.githubusercontent.com/assets/4185328/22693960/48cbafce-ed3d-11e6-8227-b369bd16f1d8.png">

**Comment by markwilliamfirth** [comment]
<img width="657" alt="screen shot 2017-02-07 at 14 06 28" src="https://cloud.githubusercontent.com/assets/5732209/22694318/ac29c924-ed3e-11e6-82c9-06e5bba69be8.png">

**Comment by iteles** [comment]
Thanks @markwilliamfirth.

Change to... Educational? Most of what we do is open source.

**Comment by markwilliamfirth** [comment]
@iteles Not sure we class as an educational institution legally. Instinctively I would have thought "Ltd Company" - are there many options?

Side note - would it be possible to add me as a DWYL LinkedIn admin? 😸

**Comment by iteles** [comment]
@markwilliamfirth You should be already!
