### ISSUE TITLE
Different logos being used

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/brand#7]
We should have brand consistency. We should agree on a logo to use consistently

![Uploading Screen Shot 2017-02-07 at 14.03.34.png…]()
<img width="265" alt="screen shot 2017-02-07 at 14 03 39" src="https://cloud.githubusercontent.com/assets/5732209/22694233/493a1a4e-ed3e-11e6-8567-59c462d59d0a.png">
<img width="356" alt="screen shot 2017-02-07 at 14 03 52" src="https://cloud.githubusercontent.com/assets/5732209/22694234/493a6d3c-ed3e-11e6-8f9b-6594c7c11790.png">
<img width="198" alt="screen shot 2017-02-07 at 14 04 34" src="https://cloud.githubusercontent.com/assets/5732209/22694259/61921c5e-ed3e-11e6-8eab-5a86bff665aa.png">

Any thoughts @iteles and @nelsonic ?

**Comment by iteles** [comment]
The actual logo is the same on all of these, as are the colours used.

Sometimes we add dwyl.io for clarity but the smaller `io` is a hangover and we should move back to all letters being the same size or no `io` at all.

**Comment by markwilliamfirth** [comment]
The colour of the heart is different though - should the tick and the "3" be the same colour or different colours? My first thought is I actually prefer the website version with the white "3"

It's important because it might affect our trade mark application.

**Comment by iteles** [comment]
The logo on the website is one colour - the tick highlights once you mouse over it so bring attention to the fact that it's a tick. We've always used one colour on everything until now (whether the teal or the white).

<img width="548" alt="screen shot 2017-02-07 at 14 12 34" src="https://cloud.githubusercontent.com/assets/4185328/22694555/996ea31c-ed3f-11e6-8662-37d437076f26.png">

**Comment by nelsonic** [comment]
I _agree_ that we should use one tone in _most_ situations for consistency.
but equally am super excited about getting these: https://github.com/dwyl/print-me/issues/22 😉
