### ISSUE TITLE
Mispronunciations and Misspellings

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/brand#9]
This issue is for tracking occurrences of mispronunciations and misspellings of DWYL.

**Comment by markwilliamfirth** [comment]
<img width="327" alt="screen shot 2017-02-15 at 12 00 57" src="https://cloud.githubusercontent.com/assets/5732209/22973635/7532ddaa-f376-11e6-8442-51811c97fcef.png">

Message from a friend who has seen and said the name (and had it explained) a number of times before and how it is spelled, yet still spelled it this way.

2017-02-15

**Comment by nelsonic** [comment]
each person that misspells the name should receive a "swag bag" in the mail 📦 
with stickers, a t-shirt, pens, notebook and keyring! ❤️ 
though this could backfire and people could _deliberately_ misspell it just to get "_free_" stuff... 😜

**Comment by jruts** [comment]
What is this Dwil you speak of? @nelsonic I will give you my home address. Goodies inc.

**Comment by nelsonic** [comment]
@jruts please send us ur home address so you can help us test our new ***Motivation***-_as-a-Service_: 

![skills](https://cloud.githubusercontent.com/assets/194400/22979152/39d8c848-f38d-11e6-8fb4-0c98d685c1c5.png)
![haters](https://cloud.githubusercontent.com/assets/194400/22978839/313449ac-f38c-11e6-913c-4240b97954d2.png)
![hi-fives-done-right](https://cloud.githubusercontent.com/assets/194400/22979092/0b410298-f38d-11e6-8a8f-21a56f1e68e2.jpg)
![mullet](https://cloud.githubusercontent.com/assets/194400/22979000/c03d00c6-f38c-11e6-94ea-24c317f5c82b.png)
![awesome](https://cloud.githubusercontent.com/assets/194400/22978969/9c873052-f38c-11e6-88f7-12053acad37e.png)

we'll send a new postcard in the mail `.forEach` week. 
Until you can _spell_ `dwyl` _correctly_...! 😜 

If peeps _don't **learn**_ `.then` the "motivation" [_escalates_](https://youtu.be/9wEnb9yIoes) over time:

![paradise-motivational-poster](https://cloud.githubusercontent.com/assets/194400/22979425/393ad574-f38e-11e6-8ae8-060038085317.jpg)
![success](https://cloud.githubusercontent.com/assets/194400/22980036/2a3def5a-f390-11e6-8ca5-9b1efac42a42.png)
![hakuna matata](https://cloud.githubusercontent.com/assets/194400/22978528/fa9f3146-f38a-11e6-9fcc-34b742f7d63e.png)
![trying](https://cloud.githubusercontent.com/assets/194400/22978670/8e0f945c-f38b-11e6-862e-27985da30694.png)

![image](https://cloud.githubusercontent.com/assets/194400/22980239/e6599ee6-f390-11e6-9cff-242aaf42e233.png)
😉

**Comment by markwilliamfirth** [comment]
@nelsonic this issue is for tracking occurrences of mispronunciations and misspellings of DWYL - am I ok to remove your comments? They don't appear to be relevant to the discussion, unless you're trying to say we shouldn't record this when it happens?

**Comment by markwilliamfirth** [comment]
On Friday Hannah from Unbound pronounced it "die-will" (she was corrected) and then later pronounced it "dwell" on the video, later at the pub she pronounced it incorrectly again. Owen didn't think it was a pronounceable word and instead thought it should be pronounced "d-w-y-l". Another person thought it was "dwill-e-o" because of the dwyl.io domain in the logo

2017-02-17
